# Generated by Django 5.2.6 on 2025-09-29 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "nis",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("guru", "Guru"), ("siswa", "Siswa")],
                        default="siswa",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Guru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(max_length=20, unique=True)),
                ("jabatan", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jadwal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jam", models.TimeField()),
                ("kegiatan", models.CharField(max_length=100)),
                ("keterangan", models.TextField(blank=True)),
                (
                    "guru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.guru"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nis", models.CharField(max_length=20, unique=True)),
                ("kelas", models.CharField(max_length=20)),
                ("jurusan", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="foto_siswa/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dokumentasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="dokumentasi/")),
                ("keterangan", models.TextField()),
                ("tanggal", models.DateField(auto_now_add=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.siswa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tugas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=100)),
                ("deskripsi", models.TextField()),
                ("deadline", models.DateField()),
                (
                    "lampiran",
                    models.FileField(
                        blank=True, null=True, upload_to="lampiran_tugas/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.guru"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressPKL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("nilai", models.IntegerField(blank=True, null=True)),
                (
                    "pdf_path",
                    models.FileField(blank=True, null=True, upload_to="progress_pdf/"),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.siswa"
                    ),
                ),
                (
                    "tugas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tugas"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TugasSiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("belum", "Belum"), ("sudah", "Sudah")],
                        default="belum",
                        max_length=10,
                    ),
                ),
                (
                    "file_jawaban",
                    models.FileField(blank=True, null=True, upload_to="jawaban_tugas/"),
                ),
                ("nilai", models.IntegerField(blank=True, null=True)),
                ("catatan", models.TextField(blank=True, null=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.siswa"
                    ),
                ),
                (
                    "tugas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tugas"
                    ),
                ),
            ],
        ),
    ]
