# Generated by Django 5.2.6 on 2025-09-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_kelas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="siswa",
            name="jurusan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.jurusan",
            ),
        ),
    ]
