# Generated by Django 5.2.6 on 2025-09-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jurusan_alter_siswa_jurusan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siswa",
            name="foto",
        ),
        migrations.AddField(
            model_name="siswa",
            name="nama",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siswa",
            name="jurusan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.jurusan",
            ),
        ),
        migrations.AlterField(
            model_name="siswa",
            name="kelas",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.kelas"
            ),
        ),
    ]
