# Generated by Django 5.2.6 on 2025-09-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_siswa_foto_siswa_nama_alter_siswa_jurusan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siswa",
            name="nama",
        ),
    ]
