# Generated by Django 5.2.6 on 2025-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_siswa_nama"),
    ]

    operations = [
        migrations.AddField(
            model_name="siswa",
            name="nama",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
